"""create auth addresses

Revision ID: 11d6c2354815
Revises: 2abc53a86940
Create Date: 2026-06-12 00:17:16.209050

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "11d6c2354815"
down_revision: str | None = "2abc53a86940"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_addresses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=60), nullable=False),
        sa.Column("zip_code", sa.String(length=9), nullable=False),
        sa.Column("street", sa.String(length=160), nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("complement", sa.String(length=120), nullable=False),
        sa.Column("neighborhood", sa.String(length=120), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_addresses_user_id"), "auth_addresses", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auth_addresses_user_id"), table_name="auth_addresses")
    op.drop_table("auth_addresses")
    # ### end Alembic commands ###
