"""create products and reviews

Revision ID: 7bdd5464c421
Revises: 52b7844c0782
Create Date: 2026-06-12 00:06:33.554140

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "7bdd5464c421"
down_revision: str | None = "52b7844c0782"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products_products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("subtype", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("image_url", sa.String(length=512), nullable=False),
        sa.Column("rating_avg", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("rating_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_products_name"), "products_products", ["name"], unique=False)
    op.create_index(op.f("ix_products_products_type"), "products_products", ["type"], unique=False)
    op.create_table(
        "products_reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("author", sa.String(length=120), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(length=2000), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name="ck_products_reviews_rating"),
        sa.ForeignKeyConstraint(["product_id"], ["products_products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_products_reviews_product_id"), "products_reviews", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_products_reviews_user_id"), "products_reviews", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_reviews_user_id"), table_name="products_reviews")
    op.drop_index(op.f("ix_products_reviews_product_id"), table_name="products_reviews")
    op.drop_table("products_reviews")
    op.drop_index(op.f("ix_products_products_type"), table_name="products_products")
    op.drop_index(op.f("ix_products_products_name"), table_name="products_products")
    op.drop_table("products_products")
    # ### end Alembic commands ###
