"""create payment methods

Revision ID: b0ee0d97cc0d
Revises: 11d6c2354815
Create Date: 2026-06-12 00:19:46.521777

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b0ee0d97cc0d"
down_revision: str | None = "11d6c2354815"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_methods_methods",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("card_last4", sa.String(length=4), nullable=True),
        sa.Column("card_brand", sa.String(length=40), nullable=True),
        sa.Column("cardholder_name", sa.String(length=120), nullable=True),
        sa.Column("card_expiry", sa.String(length=4), nullable=True),
        sa.Column("pix_key", sa.String(length=140), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "type IN ('credit_card', 'pix', 'boleto')", name="ck_payment_methods_type"
        ),
        sa.CheckConstraint(
            "card_last4 IS NULL OR char_length(card_last4) = 4",
            name="ck_payment_methods_card_last4_len",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_methods_methods_user_id"),
        "payment_methods_methods",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_methods_methods_user_id"), table_name="payment_methods_methods")
    op.drop_table("payment_methods_methods")
    # ### end Alembic commands ###
