"""create orders and order items

Revision ID: 2abc53a86940
Revises: 57b1073cc5f3
Create Date: 2026-06-12 00:14:08.165856

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "2abc53a86940"
down_revision: str | None = "57b1073cc5f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders_orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("payment_method", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_orders_user_id"), "orders_orders", ["user_id"], unique=False)
    op.create_table(
        "orders_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("product_name", sa.String(length=160), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=512), nullable=False),
        sa.Column("rating_avg", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("rating_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders_orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_items_order_id"), "orders_items", ["order_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_items_order_id"), table_name="orders_items")
    op.drop_table("orders_items")
    op.drop_index(op.f("ix_orders_orders_user_id"), table_name="orders_orders")
    op.drop_table("orders_orders")
    # ### end Alembic commands ###
