"""create support messages

Revision ID: 60934c36c65d
Revises: 95088bb8eee7
Create Date: 2026-06-12 00:44:46.928555

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "60934c36c65d"
down_revision: str | None = "95088bb8eee7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "support_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("sender", sa.String(length=16), nullable=False),
        sa.Column("body", sa.String(length=2000), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("sender IN ('user', 'support')", name="ck_support_messages_sender"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_support_messages_user_id"), "support_messages", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_support_messages_user_id"), table_name="support_messages")
    op.drop_table("support_messages")
    # ### end Alembic commands ###
