"""create notifications device tokens

Revision ID: 95088bb8eee7
Revises: b0ee0d97cc0d
Create Date: 2026-06-12 00:37:29.894285

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "95088bb8eee7"
down_revision: str | None = "b0ee0d97cc0d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications_device_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "platform IN ('android', 'ios', 'web')", name="ck_notifications_device_tokens_platform"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_device_tokens_token"),
        "notifications_device_tokens",
        ["token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_notifications_device_tokens_user_id"),
        "notifications_device_tokens",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_notifications_device_tokens_user_id"), table_name="notifications_device_tokens"
    )
    op.drop_index(
        op.f("ix_notifications_device_tokens_token"), table_name="notifications_device_tokens"
    )
    op.drop_table("notifications_device_tokens")
    # ### end Alembic commands ###
