"""baseline schema

Revision ID: 559862df2d79
Revises:
Create Date: 2026-08-03 01:46:13.670366

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "559862df2d79"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fornecedores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("contato", sa.String(length=150), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pedidos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aluno_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("endereco_entrega", sa.Text(), nullable=False),
        sa.Column("valor_total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("separador_id", sa.UUID(), nullable=True),
        sa.Column("entregador_id", sa.UUID(), nullable=True),
        sa.Column("transportadora_nome", sa.String(length=100), nullable=True),
        sa.Column("data_prevista_entrega", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pedidos_aluno_id"), "pedidos", ["aluno_id"], unique=False)
    op.create_index(op.f("ix_pedidos_entregador_id"), "pedidos", ["entregador_id"], unique=False)
    op.create_index(op.f("ix_pedidos_separador_id"), "pedidos", ["separador_id"], unique=False)
    op.create_index(op.f("ix_pedidos_status"), "pedidos", ["status"], unique=False)
    op.create_table(
        "produtos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=True),
        sa.Column("preco", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("categoria", sa.String(length=50), nullable=True),
        sa.Column("imagem_url", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "estoque",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("produto_id", sa.Integer(), nullable=True),
        sa.Column("fornecedor_id", sa.Integer(), nullable=True),
        sa.Column("quantidade", sa.Integer(), nullable=False),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["fornecedor_id"],
            ["fornecedores.id"],
        ),
        sa.ForeignKeyConstraint(
            ["produto_id"],
            ["produtos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("produto_id", "fornecedor_id", name="uq_produto_fornecedor"),
    )
    op.create_table(
        "ocorrencias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pedido_id", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("produto_id", sa.Integer(), nullable=True),
        sa.Column("produtos_sugeridos", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("produto_escolhido_id", sa.Integer(), nullable=True),
        sa.Column("nova_data_sugerida", sa.DateTime(timezone=True), nullable=True),
        sa.Column("motivo", sa.Text(), nullable=False),
        sa.Column("resolucao", sa.String(length=30), nullable=True),
        sa.Column("criado_por", sa.UUID(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("resolvido_em", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedidos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["produto_escolhido_id"],
            ["produtos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["produto_id"],
            ["produtos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ocorrencias_pedido_id"), "ocorrencias", ["pedido_id"], unique=False)
    op.create_index(op.f("ix_ocorrencias_status"), "ocorrencias", ["status"], unique=False)
    op.create_table(
        "pedido_itens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pedido_id", sa.Integer(), nullable=True),
        sa.Column("produto_id", sa.Integer(), nullable=True),
        sa.Column("fornecedor_id", sa.Integer(), nullable=True),
        sa.Column("quantidade", sa.Integer(), nullable=False),
        sa.Column("preco_unitario", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["fornecedor_id"],
            ["fornecedores.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedidos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["produto_id"],
            ["produtos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pedido_status_historico",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pedido_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("observacao", sa.Text(), nullable=True),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedidos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pedido_status_historico")
    op.drop_table("pedido_itens")
    op.drop_index(op.f("ix_ocorrencias_status"), table_name="ocorrencias")
    op.drop_index(op.f("ix_ocorrencias_pedido_id"), table_name="ocorrencias")
    op.drop_table("ocorrencias")
    op.drop_table("estoque")
    op.drop_table("produtos")
    op.drop_index(op.f("ix_pedidos_status"), table_name="pedidos")
    op.drop_index(op.f("ix_pedidos_separador_id"), table_name="pedidos")
    op.drop_index(op.f("ix_pedidos_entregador_id"), table_name="pedidos")
    op.drop_index(op.f("ix_pedidos_aluno_id"), table_name="pedidos")
    op.drop_table("pedidos")
    op.drop_table("fornecedores")
    # ### end Alembic commands ###
