"""one default per user index

Revision ID: 942f75a9a3f2
Revises: 6c409ccb480c
Create Date: 2026-08-07 15:43:52.255468

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "942f75a9a3f2"
down_revision: str | Sequence[str] | None = "6c409ccb480c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_payment_methods_one_default_per_user",
        "payment_methods",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_default"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_payment_methods_one_default_per_user",
        table_name="payment_methods",
        postgresql_where=sa.text("is_default"),
    )
    # ### end Alembic commands ###
