"""products catalog columns

Revision ID: d3a5f5cd6ea8
Revises: 1308bb221890
Create Date: 2026-08-07 10:44:58.461646

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3a5f5cd6ea8"
down_revision: str | Sequence[str] | None = "1308bb221890"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("subtype", sa.String(length=64), server_default=sa.text("''"), nullable=False),
    )
    op.add_column(
        "products",
        sa.Column(
            "rating_avg",
            sa.Numeric(precision=3, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.add_column(
        "products",
        sa.Column("rating_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "products",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "products",
        "name",
        existing_type=sa.VARCHAR(length=150),
        type_=sa.String(length=160),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "type",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=64),
        nullable=False,
    )
    op.alter_column(
        "products",
        "description",
        existing_type=sa.TEXT(),
        server_default=sa.text("''"),
        nullable=False,
    )
    op.alter_column(
        "products",
        "image_url",
        existing_type=sa.VARCHAR(length=255),
        server_default=sa.text("''"),
        type_=sa.String(length=512),
        nullable=False,
    )
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=False)
    op.create_index(op.f("ix_products_type"), "products", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_type"), table_name="products")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.alter_column(
        "products",
        "image_url",
        existing_type=sa.String(length=512),
        server_default=None,
        type_=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "products", "description", existing_type=sa.TEXT(), server_default=None, nullable=True
    )
    op.alter_column(
        "products",
        "type",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "products",
        "name",
        existing_type=sa.String(length=160),
        type_=sa.VARCHAR(length=150),
        existing_nullable=False,
    )
    op.drop_column("products", "updated_at")
    op.drop_column("products", "created_at")
    op.drop_column("products", "rating_count")
    op.drop_column("products", "rating_avg")
    op.drop_column("products", "subtype")
    # ### end Alembic commands ###
