"""baseline schema

Revision ID: 7b44c873024d
Revises:
Create Date: 2026-08-03 04:32:35.262958

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b44c873024d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aluno_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column(
            "platform", sa.String(length=20), server_default=sa.text("'android'"), nullable=False
        ),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("aluno_id", "token", name="uq_aluno_token"),
    )
    op.create_index(op.f("ix_device_tokens_aluno_id"), "device_tokens", ["aluno_id"], unique=False)
    op.create_index(op.f("ix_device_tokens_token"), "device_tokens", ["token"], unique=False)
    op.create_table(
        "notificacoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aluno_id", sa.UUID(), nullable=False),
        sa.Column("titulo", sa.String(length=150), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=False),
        sa.Column("tipo", sa.String(length=30), nullable=False),
        sa.Column("pedido_id", sa.Integer(), nullable=True),
        sa.Column("ocorrencia_id", sa.Integer(), nullable=True),
        sa.Column("lido_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notificacoes_aluno_id"), "notificacoes", ["aluno_id"], unique=False)
    op.create_index(op.f("ix_notificacoes_lido_em"), "notificacoes", ["lido_em"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notificacoes_lido_em"), table_name="notificacoes")
    op.drop_index(op.f("ix_notificacoes_aluno_id"), table_name="notificacoes")
    op.drop_table("notificacoes")
    op.drop_index(op.f("ix_device_tokens_token"), table_name="device_tokens")
    op.drop_index(op.f("ix_device_tokens_aluno_id"), table_name="device_tokens")
    op.drop_table("device_tokens")
    # ### end Alembic commands ###
