"""baseline schema

Revision ID: 21283ddca6a5
Revises:
Create Date: 2026-08-03 00:19:00.619358

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21283ddca6a5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "materia",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tema",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("materia_id", sa.Integer(), nullable=True),
        sa.Column("nome", sa.String(length=100), nullable=False),
        sa.Column("ordem", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["materia_id"],
            ["materia.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subtema",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tema_id", sa.Integer(), nullable=True),
        sa.Column("nome", sa.String(length=100), nullable=False),
        sa.Column("ordem", sa.Integer(), nullable=False),
        sa.Column("videoaula_base_url", sa.String(length=255), nullable=True),
        sa.Column("videoaula_revisao_url", sa.String(length=255), nullable=True),
        sa.Column("descricao_ia", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tema_id"],
            ["tema.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "aluno_tema_progresso",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aluno_id", sa.UUID(), nullable=False),
        sa.Column("subtema_id", sa.Integer(), nullable=True),
        sa.Column("nivel_dominio", sa.Float(), nullable=True),
        sa.Column("intervalo_dias", sa.Float(), nullable=True),
        sa.Column("streak_acertos", sa.Integer(), nullable=True),
        sa.Column("ultima_revisao", sa.DateTime(timezone=True), nullable=True),
        sa.Column("proxima_revisao", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_respondidas", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["subtema_id"],
            ["subtema.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("aluno_id", "subtema_id", name="uq_aluno_subtema"),
    )
    op.create_index(
        op.f("ix_aluno_tema_progresso_aluno_id"), "aluno_tema_progresso", ["aluno_id"], unique=False
    )
    op.create_index(
        op.f("ix_aluno_tema_progresso_proxima_revisao"),
        "aluno_tema_progresso",
        ["proxima_revisao"],
        unique=False,
    )
    op.create_table(
        "questao",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subtema_id", sa.Integer(), nullable=True),
        sa.Column("enunciado", sa.Text(), nullable=False),
        sa.Column("alternativas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("gabarito", sa.String(length=1), nullable=False),
        sa.Column("nivel_dificuldade", sa.Integer(), nullable=False),
        sa.Column("fonte", sa.String(length=50), nullable=True),
        sa.Column("ano", sa.Integer(), nullable=True),
        sa.CheckConstraint("nivel_dificuldade BETWEEN 1 AND 3", name="ck_nivel_dificuldade"),
        sa.ForeignKeyConstraint(
            ["subtema_id"],
            ["subtema.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_questao_subtema_id"), "questao", ["subtema_id"], unique=False)
    op.create_table(
        "diagnostico_resposta",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aluno_id", sa.UUID(), nullable=False),
        sa.Column("questao_id", sa.Integer(), nullable=True),
        sa.Column("alternativa_escolhida", sa.String(length=1), nullable=False),
        sa.Column("acertou", sa.Boolean(), nullable=False),
        sa.Column(
            "respondido_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["questao_id"],
            ["questao.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_diagnostico_resposta_aluno_id"), "diagnostico_resposta", ["aluno_id"], unique=False
    )
    op.create_index(
        op.f("ix_diagnostico_resposta_questao_id"),
        "diagnostico_resposta",
        ["questao_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_diagnostico_resposta_questao_id"), table_name="diagnostico_resposta")
    op.drop_index(op.f("ix_diagnostico_resposta_aluno_id"), table_name="diagnostico_resposta")
    op.drop_table("diagnostico_resposta")
    op.drop_index(op.f("ix_questao_subtema_id"), table_name="questao")
    op.drop_table("questao")
    op.drop_index(
        op.f("ix_aluno_tema_progresso_proxima_revisao"), table_name="aluno_tema_progresso"
    )
    op.drop_index(op.f("ix_aluno_tema_progresso_aluno_id"), table_name="aluno_tema_progresso")
    op.drop_table("aluno_tema_progresso")
    op.drop_table("subtema")
    op.drop_table("tema")
    op.drop_table("materia")
    # ### end Alembic commands ###
