"""restore database level defaults

Revision ID: b9e63fa43f39
Revises: 21283ddca6a5
Create Date: 2026-08-03 23:36:19.517289

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9e63fa43f39"
down_revision: str | Sequence[str] | None = "21283ddca6a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "aluno_tema_progresso",
        "nivel_dominio",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=sa.text("0.0"),
        existing_nullable=True,
    )
    op.alter_column(
        "aluno_tema_progresso",
        "intervalo_dias",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=sa.text("1.0"),
        existing_nullable=True,
    )
    op.alter_column(
        "aluno_tema_progresso",
        "streak_acertos",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=True,
    )
    op.alter_column(
        "aluno_tema_progresso",
        "total_respondidas",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=True,
    )
    op.alter_column(
        "questao",
        "fonte",
        existing_type=sa.VARCHAR(length=50),
        server_default="ENEM",
        existing_nullable=True,
    )
    op.alter_column(
        "subtema",
        "ordem",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "tema",
        "ordem",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tema", "ordem", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "subtema", "ordem", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "questao",
        "fonte",
        existing_type=sa.VARCHAR(length=50),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "aluno_tema_progresso",
        "total_respondidas",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "aluno_tema_progresso",
        "streak_acertos",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "aluno_tema_progresso",
        "intervalo_dias",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "aluno_tema_progresso",
        "nivel_dominio",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=None,
        existing_nullable=True,
    )
    # ### end Alembic commands ###
