"""restore database level defaults

Revision ID: 0f7c6034f61f
Revises: 8e682c1411bd
Create Date: 2026-08-03 23:36:08.179475

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f7c6034f61f"
down_revision: str | Sequence[str] | None = "8e682c1411bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "addresses",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "addresses",
        "label",
        existing_type=sa.VARCHAR(length=60),
        server_default="",
        existing_nullable=False,
    )
    op.alter_column(
        "addresses",
        "complement",
        existing_type=sa.VARCHAR(length=120),
        server_default="",
        existing_nullable=False,
    )
    op.alter_column(
        "addresses",
        "is_favorite",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "password_reset_codes",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "password_reset_codes",
        "usado",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=20),
        server_default="student",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "ativo",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "ativo", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=True
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "password_reset_codes",
        "usado",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "password_reset_codes",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "addresses",
        "is_favorite",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "addresses",
        "complement",
        existing_type=sa.VARCHAR(length=120),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "addresses",
        "label",
        existing_type=sa.VARCHAR(length=60),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "addresses", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False
    )
    # ### end Alembic commands ###
